#include "config.h"
#include <cmath>

// IMU Configuration, set to false to disable IMU
const bool useIMU = false;

// Dry run configuration - angle to stop time mapping (values in milliseconds)
const std::unordered_map<double, unsigned long> DRY_RUN_STOP_TIMES = {
    {45, 1250},  // 45°
    {90, 1600},  // 90°
    {135, 1900}, // 135°
    {180, 2200}  // 180°
};

// Robot physical parameters
const double WHEEL_DISTANCE = 155.8; // Distance between wheels in mm

// Turn compensation factors
const double LEFT_TURN_COMPENSATION = 90.01 / 90.0;  // Correction for left turns
const double RIGHT_TURN_COMPENSATION = 90.00 / 90.0; // Correction for right turns


// test configuration
const double rt = 93.5;   // 94.35 //So I think that the kp thing applies only to IMU, at least thats what the ai said
const double lt = 94.2; // 95
const double rh = (rt / 2);
const double lh = (lt / 2);
const double a = 0.75; //cos^-1(199.8/200) is how we determined it
const double d = std::sqrt(2); // √2, for diagonal movement

// PID control parameters
const double TURN_PID_KP = 160.0;
const double TURN_PID_KI = 0.0;
const double TURN_PID_KD = 0.0;

// void function adjust(int x, int y) {
      
// }

// test configuration
CommandSequence origtestSequence = CommandSequence()
                                   .l()
                                   .l()
                                   .l()
                                   .l()
                                   .stop(3000)
                                   .l()
                                   .l()
                                   .l()
                                   .l()
                                   .stop(5000)
                                   .r()
                                   .r()
                                   .r()
                                   .r()
                                   .stop(3000)
                                   .r()
                                   .r()
                                   .r()
                                   .r();
// updated test sequence
CommandSequence testSequence = CommandSequence()
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  .l(lt)
                                  // .f(2500)
                                  // .f(2500)
                                  // .f(2500)
                                  // .f(5000) 
                                  
                                 
                                   ;

// competition configuration
// Define total stop time
const unsigned long totalStopTime = 0; // ms
// example run - gullso
CommandSequence OrigrunSequence = CommandSequence()
                                //   .f(250 + 42 + 500 + 300)
                                //   .b(300 + 500)
                                //   .r()
                                //   .f(1000)
                                //   .l()
                                //   .f()
                                //   .r()
                                //   .f()
                                //   .l()
                                //   .f(1000 + 300)
                                //   .b(300 + 500)
                                //   .l()
                                //   .f()
                                //   .r()
                                //   .f(1000)
                                //   .l()
                                //   .f(500 + 300)
                                //   .b(300 + 500)
                                //   .l()
                                //   .f(1000)
                                //   .r()
                                //   .f()
                                //   .l()
                                //   .f(1000)
                                //   .l()
                                //   .f(500 + 300)
                                //   .b(300 + 500)
                                //   .l()
                                //   .f(1500)
                                //   .l()
                                //   .f(500 - 42)
                                ;


// updated runsequence - test
// .l(a)
// .r(a)
CommandSequence runSequence = CommandSequence() // 66
.r(rh)
.f(250 * d)
.r(rh)
.f(1000)
.stop(1000)
.l(lh)
.f(350 * d)
.stop(1000)
.b(350 * d)
.l(lh + lt)
.stop(1000)
.f(1000)
.r(rh)
.stop(1000)
.f(250*d)
.r(rt)
.stop(1000)
.f(250 * d)
.r(rh)
.stop(1000)
.f(750)
.l(lt)
.f(500)
.l(lt)
.stop(1000)
.f(500)
.r(rt)
.f(500)
.r(rt)
.stop(1000)
.f(750)
.r(rh)
.f(300 * d)
.stop(1000)
.b(300 * d)
.r(rt + rh)
.f(1750)
.stop(1000)
.l(lt)
.f(1000)
.l(lt * 2)
.stop(1000)
.b(500)
.r(rt)
.stop(1000)
.f(500)
.l(lt)
.stop(500)
.f(1000)
// ----------------------------------------- GullSo kind of perfected -----------------------------------------------
// .r(rh)
// .f(250 * d)
// .stop(2000)
// .r(rh)
// .f(500)
// .stop(2000)
// .l(lh)
// .f(800 * d)
// .stop(2000)
// .b(800 * d)
// .l(lh + lt)
// .stop(2000)
// .f(750)
// .stop(2000)
// .r(rt)
// .stop(2000)
// .f(500)
// .stop(2000)
// .l(lt)
// .f(350)
// .stop(2000)
// .b(350)
// .r(rt)
// .f(500)
// .r(rt)
// .f(500)
// .stop(2000)
// .l(lt)
// .f(350)
// .stop(2000)
// .b(350)
// .l(lt)
// .f(1000)
// .l(12.5 + 71.5)
// .b(5.28 * 10)
// .adjust()
//5.2, 61.5
// -------------------------------------------------- testing ---------------------------------------------------------------
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)
// .r(rt)

//-----------------------------------------------some run sequence I forgot --------------------------------------------------
// .l(lh)
// .f(250 * d)
// .stop(1000)
// .l(lh)
// .f(750)
// .r(rt)
// .f(250)
// .stop(1000)
// .r(rh)
// .f(300 * d)
// .b(550 * d)
// .r(rh)
// .f(1250)
// .stop(1000)
// .l(lt)
// .f(750)
// .l(lh)
// .stop(1000)
// .f(250 * d)
// .r(rt)
// .f(500 * d)
// .r(rt)
// .f(250 * d)
// .r(rh)
// .f(1100)
// .stop(1000)
// .b(1350)
// .l(lt)
// .stop(1000)
// .f(750)
// .r(rt + rh)
// .f(300 * d)
// .b(300 * d)
// .r(rh)
// .stop(1000)
// .f(1000)
// .l(lh)
// .stop(500)
// .f(500 * d)
// .r(rh)
// .f(750)
// .stop(1000)
// .r(rt)
// .f(500)
// .r(rt)
// .f(300)
// .b(300)





// ----------------------------- SWHS RUN PERFECTED -----------------------------------------------
                                  // .f(500)
                                  // .stop(2000)
                                  // .r(rh)
                                  // .stop(2000)
                                  // .f(1300 * d)
                                  // .stop(2000)
                                  // .b(300 * d)
                                  // .stop(2000)
                                  // .l(lt)
                                  // .stop(2000)
                                  // .f(750 * d)
                                  // .stop(2000)
                                  // .r(rt + rh) 
                                  // .stop(2000)
                                  // .f(100)
                                  // .stop(2000)
                                  // .b(100)
                                  // .r(rh)
                                  // .f(750 * d)
                                  // .r(rh)
                                  // .f(500)
                                  // .l(lh)
                                  // .f(500 * d)
                                  // .r(rt)
                                  // .f(300 * d)
                                  // .b(300 * d)
                                  // .r(rt + rh)
                                  // .f(550)
                                  // .b(550)
                                  // .l(lh)
                                  // .f(750 * d)
                                  // .l(lh)
                                  // .f(230)




// ---------------------------- GGSO RUN PERFECTED -----------------------------------------------  
                                // .l(lh)
                                // .f(250 * d)
                                // .r(rt + rh)
                                // .f(1250)
                                // .r(rt)
                                // .b(250)
                                // .r(rt + rh)
                                // .f(500 * d)
                                // .r(rh)
                                // .f(1000)
                                // .r(rh)
                                // .f(250 * d)
                                // .r(rh)
                                // .f(250)
                                // .r(rt)
                                // .f(300)
                                // .b(300)
                                // .r(rt)
                                // .f(500)
                                // .l(lt)
                                // .f(250)
                                // .r(rh)
                                // .f(500 * d)
                                // .r(rt)
                                // .f(500 * d)
                                // .r(rt)
                                // .f(350 * d)
                                // .b(350 * d)
                                // .r(rt + rh)
                                // .f(1100)
                                // .b(1100)
                                // .l(lh)
                                // .f(500 * d)
                                // .r(rh)
                                // .f(850)
                                // .l(lh + lt)
                                // .f(400 * d)
                                // .b(400 * d)
                                // .l(lh)
                                // .f(130)
;
